version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile # Utiliza el Dockerfile personalizado
    ports:
      - "8888:80"
    volumes:
      - ./php:/var/www/html
    restart: always
