import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;
import com.sun.net.httpserver.HttpServer;
import java.io.IOException;
import java.io.OutputStream;
import java.net.InetSocketAddress;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class LicenseServer {

    private static final int SERVER_PORT = 8000;
        private static final String DB_URL = "jdbc:sqlite:licenses.db";

            public static void main(String[] args) throws IOException {
                    HttpServer server = HttpServer.create(new InetSocketAddress(SERVER_PORT), 0);
                            server.createContext("/verificarLicencia", new LicenseHandler());
                                    server.setExecutor(null); // Usaremos el hilo predeterminado
                                            server.start();
                                                    System.out.println("Servidor HTTP iniciado en el puerto " + SERVER_PORT);
                                                        }

                                                            static class LicenseHandler implements HttpHandler {
                                                                    @Override
                                                                            public void handle(HttpExchange exchange) throws IOException {
                                                                                        String requestMethod = exchange.getRequestMethod();
                                                                                                    if (requestMethod.equalsIgnoreCase("GET")) {
                                                                                                                    String query = exchange.getRequestURI().getQuery();
                                                                                                                                    String[] params = query.split("="); // Suponiendo que la solicitud tiene la forma "?clave=valor"
                                                                                                                                                    if (params.length == 2 && params[0].equals("clave")) {
                                                                                                                                                                        String clave = params[1];
                                                                                                                                                                                            String licenseData = getLicenseData(clave);
                                                                                                                                                                                                                if (licenseData != null) {
                                                                                                                                                                                                                                        exchange.sendResponseHeaders(200, licenseData.length());
                                                                                                                                                                                                                                                                OutputStream os = exchange.getResponseBody();
                                                                                                                                                                                                                                                                                        os.write(licenseData.getBytes());
                                                                                                                                                                                                                                                                                                                os.close();
                                                                                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                                                                                            String response = "Licencia no encontrada";
                                                                                                                                                                                                                                                                                                                                                                                    exchange.sendResponseHeaders(404, response.length());
                                                                                                                                                                                                                                                                                                                                                                                                            OutputStream os = exchange.getResponseBody();
                                                                                                                                                                                                                                                                                                                                                                                                                                    os.write(response.getBytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                            os.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    String response = "Solicitud inválida";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        exchange.sendResponseHeaders(400, response.length());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            OutputStream os = exchange.getResponseBody();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.write(response.getBytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    os.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                String response = "Método no permitido";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                exchange.sendResponseHeaders(405, response.length());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                OutputStream os = exchange.getResponseBody();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.write(response.getBytes());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                os.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            private String getLicenseData(String clave) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        String sql = "SELECT clave, valida FROM licenses WHERE clave = ?";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try (Connection conn = DriverManager.getConnection(DB_URL);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     PreparedStatement pstmt = conn.prepareStatement(sql)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     pstmt.setString(1, clave);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ResultSet rs = pstmt.executeQuery();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if (rs.next()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         String claveLicencia = rs.getString("clave");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             boolean esValida = rs.getBoolean("valida");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return "Clave de licencia: " + claveLicencia + ", Valida: " + esValida;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             } catch (SQLException e) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             e.printStackTrace();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }